echo Computing diff of raw and unified datasets...
diff --brief ~/bitcoin-json/ ~/unified-bitcoin-json/ | grep -v differ | grep "/bitcoin" | awk '{print $4}'  > .unified-to-process.txt
echo Updating unified...
python3 block-json-to-unified.py .unified-to-process.txt

